/**
 * CopyPaste.me
 *
 * @author Sebastian Kersten (@supertaboo)
 */

'use strict';


module.exports = function()
{

};

module.exports.prototype = {

    // connect primary device
    REQUEST_PRIMARYDEVICE_CONNECT: 'REQUEST_PRIMARYDEVICE_CONNECT',
    UPDATE_PRIMARYDEVICE_CONNECTED: 'UPDATE_PRIMARYDEVICE_CONNECTED',

    // connect secondary device
    REQUEST_SECONDARYDEVICE_CONNECT_BY_QR: 'REQUEST_SECONDARYDEVICE_CONNECT_BY_QR',
    UPDATE_SECONDARYDEVICE_CONNECTED_BY_QR: 'UPDATE_SECONDARYDEVICE_CONNECTED_BY_QR',
    ERROR_SECONDARYDEVICE_CONNECT_BY_QR_TOKEN_NOT_FOUND: 'ERROR_SECONDARYDEVICE_CONNECT_BY_QR_TOKEN_NOT_FOUND',

    // setup manual connection
    REQUEST_PRIMARYDEVICE_MANUALCODE: 'REQUEST_PRIMARYDEVICE_MANUALCODE',
    UPDATE_PRIMARYDEVICE_MANUALCODE: 'UPDATE_PRIMARYDEVICE_MANUALCODE',
    REQUEST_SECONDARYDEVICE_CONNECT_BY_MANUALCODE: 'REQUEST_SECONDARYDEVICE_CONNECT_BY_MANUALCODE',
    ERROR_SECONDARYDEVICE_CONNECT_BY_MANUALCODE_TOKEN_NOT_FOUND: 'ERROR_SECONDARYDEVICE_CONNECT_BY_MANUALCODE_TOKEN_NOT_FOUND',
    UPDATE_SECONDARYDEVICE_MANUALCODE_ACCEPTED: 'UPDATE_SECONDARYDEVICE_MANUALCODE_ACCEPTED',
    REQUEST_SECONDARYDEVICE_MANUALCODE_HANDSHAKE: 'REQUEST_SECONDARYDEVICE_MANUALCODE_HANDSHAKE',
    REQUEST_PRIMARYDEVICE_MANUALCODE_CONFIRMATION: 'REQUEST_PRIMARYDEVICE_MANUALCODE_CONFIRMATION',
    REQUEST_PRIMARYDEVICE_MANUALCODE_CONFIRMED: 'REQUEST_SECONDARYDEVICE_MANUALCODE_CONFIRMED',
    UPDATE_SECONDARYDEVICE_CONNECTED_BY_MANUALCODE: 'UPDATE_SECONDARYDEVICE_CONNECTED_BY_MANUALCODE',

    // connection management for both devices
    REQUEST_DEVICE_RECONNECT: 'REQUEST_DEVICE_RECONNECT',
    UPDATE_DEVICE_RECONNECTED: 'UPDATE_DEVICE_RECONNECTED',
    ERROR_DEVICE_RECONNECT_DEVICEID_NOT_FOUND: 'ERROR_DEVICE_RECONNECT_DEVICEID_NOT_FOUND',
    UPDATE_OTHERDEVICE_CONNECTED: 'UPDATE_OTHERDEVICE_CONNECTED',
    UPDATE_OTHERDEVICE_DISCONNECTED: 'UPDATE_OTHERDEVICE_DISCONNECTED',
    UPDATE_OTHERDEVICE_RECONNECTED: 'UPDATE_OTHERDEVICE_RECONNECTED',

    // sharing
    REQUEST_TOGGLE_MANUALCONNECT: 'REQUEST_TOGGLE_MANUALCONNECT',
    SEND_DATA: 'SEND_DATA',
    RECEIVE_DATA: 'RECEIVE_DATA',

    // security
    REQUEST_PRIMARYDEVICE_FRESH_TOKEN: 'REQUEST_PRIMARYDEVICE_FRESH_TOKEN',
    UPDATE_PRIMARYDEVICE_FRESH_TOKEN: 'UPDATE_PRIMARYDEVICE_FRESH_TOKEN',
    ERROR_SECURITY_COMPROMISED: 'ERROR_SECURITY_COMPROMISED',

    // functionality
    REQUEST_TOGGLE_DIRECTION: 'REQUEST_TOGGLE_DIRECTION',
    UPDATE_TOGGLE_DIRECTION: 'UPDATE_TOGGLE_DIRECTION',

};
