/**
 * CopyPaste.me
 *
 * @author Sebastian Kersten (@supertaboo)
 */

'use strict';


module.exports = function()
{

};

module.exports.prototype = {

    PRIMARYDEVICE_CONNECT: 'PRIMARYDEVICE_CONNECT',
    PRIMARYDEVICE_CONNECTED: 'PRIMARYDEVICE_CONNECTED',
    PRIMARYDEVICE_RECONNECT: 'PRIMARYDEVICE_RECONNECT',
    PRIMARYDEVICE_RECONNECTED: 'PRIMARYDEVICE_RECONNECTED',

    REQUEST_TOKEN_REFRESH: 'REQUEST_TOKEN_REFRESH',
    PRIMARYDEVICE_REQUEST_TOKEN_REFRESH: 'PRIMARYDEVICE_REQUEST_TOKEN_REFRESH',
    PRIMARYDEVICE_TOKEN_REFRESHED: 'PRIMARYDEVICE_TOKEN_REFRESHED',


    SECONDARYDEVICE_CONNECT_BY_QR: 'SECONDARYDEVICE_CONNECT_BY_QR',
    SECONDARYDEVICE_CONNECTED: 'SECONDARYDEVICE_CONNECTED',
    SECONDARYDEVICE_RECONNECT: 'SECONDARYDEVICE_RECONNECT',
    SECONDARYDEVICE_RECONNECTED: 'SECONDARYDEVICE_RECONNECTED',

    SECONDARYDEVICE_CONNECT_TOKEN_NOT_FOUND: 'SECONDARYDEVICE_CONNECT_TOKEN_NOT_FOUND',


    RECONNECT_DEVICEID_NOT_FOUND: 'RECONNECT_DEVICEID_NOT_FOUND',


    // events
    REQUEST_TOGGLE_MANUALCONNECT: 'request_toggle_manualconnect',
    REQUEST_MANUALCODE: 'request_manualcode',
    REQUEST_CONNECTION_BY_MANUALCODE: 'request_connection_by_manualcode',
    MANUALCODE_NOT_FOUND: 'manualcode_not_found',

    // security
    SECURITY_COMPROMISED: 'SECURITY_COMPROMISED'

};
