/**
 * CopyPaste.me
 *
 * @author Sebastian Kersten (@supertaboo)
 */

'use strict';


module.exports = function()
{

};

module.exports.prototype = {

    PRIMARYDEVICE_CONNECT: 'PRIMARYDEVICE_CONNECT',
    PRIMARYDEVICE_CONNECTED: 'PRIMARYDEVICE_CONNECTED',
    PRIMARYDEVICE_RECONNECT: 'PRIMARYDEVICE_RECONNECT',

    REQUEST_TOKEN_REFRESH: 'REQUEST_TOKEN_REFRESH',
    PRIMARYDEVICE_REQUEST_TOKEN_REFRESH: 'PRIMARYDEVICE_REQUEST_TOKEN_REFRESH',
    PRIMARYDEVICE_TOKEN_REFRESHED: 'PRIMARYDEVICE_TOKEN_REFRESHED',


    SECONDARYDEVICE_CONNECT: 'SECONDARYDEVICE_CONNECT',
    SECONDARYDEVICE_CONNECT_TOKEN_NOT_FOUND: 'SECONDARYDEVICE_CONNECT_TOKEN_NOT_FOUND',
    SECONDARYDEVICE_RECONNECT: 'SECONDARYDEVICE_RECONNECT',

    // events
    REQUEST_TOGGLE_MANUALCONNECT: 'request_toggle_manualconnect',
    REQUEST_MANUALCODE: 'request_manualcode',
    REQUEST_CONNECTION_BY_MANUALCODE: 'request_connection_by_manualcode',
    MANUALCODE_NOT_FOUND: 'manualcode_not_found'

};
